import { Peliculas } from "./Peliculas"

const peliculas = Peliculas;

export const Funciones = [
        {
            id: 0,
            id_pelicula: peliculas[0].id,
            nombre: peliculas[0].nombre,
            tresD: true,
            subtitulada: false,
            PEGI: peliculas[0].PEGI,
            sinopsis: peliculas[0].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[0].estreno,
            poster: peliculas[0].poster,
            imagen: peliculas[0].imagen
        },
        {
            id: 1,
            id_pelicula: peliculas[0].id,
            nombre: peliculas[0].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[0].PEGI,
            sinopsis: peliculas[0].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[0].estreno,
            poster: peliculas[0].poster,
            imagen: peliculas[0].imagen
        },
        {
            id: 2,
            id_pelicula: peliculas[0].id,
            nombre: peliculas[0].nombre,
            tresD: true,
            subtitulada: true,
            PEGI: peliculas[0].PEGI,
            sinopsis: peliculas[0].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[0].estreno,
            poster: peliculas[0].poster,
            imagen: peliculas[0].imagen
        },
        {
            id: 3,
            id_pelicula: peliculas[1].id,
            nombre: peliculas[1].nombre,
            tresD: true,
            subtitulada: false,
            PEGI: peliculas[1].PEGI,
            sinopsis: peliculas[1].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[1].estreno,
            poster: peliculas[1].poster,
            imagen: peliculas[1].imagen
        },
        {
            id: 4,
            id_pelicula: peliculas[1].id,
            nombre: peliculas[1].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[1].PEGI,
            sinopsis: peliculas[1].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[1].estreno,
            poster: peliculas[1].poster,
            imagen: peliculas[1].imagen
        },
        {
            id: 5,
            id_pelicula: peliculas[1].id,
            nombre: peliculas[1].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[1].PEGI,
            sinopsis: peliculas[1].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[1].estreno,
            poster: peliculas[1].poster,
            imagen: peliculas[1].imagen
        },
        {
            id: 6,
            id_pelicula: peliculas[2].id,
            nombre: peliculas[2].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[2].PEGI,
            sinopsis: peliculas[2].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[2].estreno,
            poster: peliculas[2].poster,
            imagen: peliculas[2].imagen
        },
        {
            id: 7,
            id_pelicula: peliculas[2].id,
            nombre: peliculas[2].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[2].PEGI,
            sinopsis: peliculas[2].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[2].estreno,
            poster: peliculas[2].poster,
            imagen: peliculas[2].imagen
        },
        {
            id: 8,
            id_pelicula: peliculas[3].id,
            nombre: peliculas[3].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[3].PEGI,
            sinopsis: peliculas[3].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[3].estreno,
            poster: peliculas[3].poster,
            imagen: peliculas[3].imagen
        },
        {
            id: 9,
            id_pelicula: peliculas[3].id,
            nombre: peliculas[3].nombre,
            tresD: true,
            subtitulada: false,
            PEGI: peliculas[3].PEGI,
            sinopsis: peliculas[3].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[3].estreno,
            poster: peliculas[3].poster,
            imagen: peliculas[3].imagen
        },
        {
            id: 10,
            id_pelicula: peliculas[3].id,
            nombre: peliculas[3].nombre,
            tresD: true,
            subtitulada: true,
            PEGI: peliculas[3].PEGI,
            sinopsis: peliculas[3].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[3].estreno,
            poster: peliculas[3].poster,
            imagen: peliculas[3].imagen
        },
        {
            id: 11,
            id_pelicula: peliculas[4].id,
            nombre: peliculas[4].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[4].PEGI,
            sinopsis: peliculas[4].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[4].estreno,
            poster: peliculas[4].poster,
            imagen: peliculas[4].imagen
        },
        {
            id: 12,
            id_pelicula: peliculas[4].id,
            nombre: peliculas[4].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[4].PEGI,
            sinopsis: peliculas[4].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[4].estreno,
            poster: peliculas[4].poster,
            imagen: peliculas[4].imagen
        },
        {
            id: 13,
            id_pelicula: peliculas[5].id,
            nombre: peliculas[5].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[5].PEGI,
            sinopsis: peliculas[5].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[5].estreno,
            poster: peliculas[5].poster,
            imagen: peliculas[5].imagen
        },
        {
            id: 14,
            id_pelicula: peliculas[5].id,
            nombre: peliculas[5].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[5].PEGI,
            sinopsis: peliculas[5].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[5].estreno,
            poster: peliculas[5].poster,
            imagen: peliculas[5].imagen
        },
        {
            id: 15,
            id_pelicula: peliculas[6].id,
            nombre: peliculas[6].nombre,
            tresD: true,
            subtitulada: false,
            PEGI: peliculas[6].PEGI,
            sinopsis: peliculas[6].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[6].estreno,
            poster: peliculas[6].poster,
            imagen: peliculas[6].imagen
        },
        {
            id: 16,
            id_pelicula: peliculas[6].id,
            nombre: peliculas[6].nombre,
            tresD: true,
            subtitulada: false,
            PEGI: peliculas[6].PEGI,
            sinopsis: peliculas[6].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[6].estreno,
            poster: peliculas[6].poster,
            imagen: peliculas[6].imagen
        },
        {
            id: 17,
            id_pelicula: peliculas[6].id,
            nombre: peliculas[6].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[6].PEGI,
            sinopsis: peliculas[6].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[6].estreno,
            poster: peliculas[6].poster,
            imagen: peliculas[6].imagen
        },
        {
            id: 18,
            id_pelicula: peliculas[7].id,
            nombre: peliculas[7].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[7].PEGI,
            sinopsis: peliculas[7].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[7].estreno,
            poster: peliculas[7].poster,
            imagen: peliculas[7].imagen
        },
        {
            id: 19,
            id_pelicula: peliculas[7].id,
            nombre: peliculas[7].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[7].PEGI,
            sinopsis: peliculas[7].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[7].estreno,
            poster: peliculas[7].poster,
            imagen: peliculas[7].imagen
        },
        {
            id: 20,
            id_pelicula: peliculas[7].id,
            nombre: peliculas[7].nombre,
            tresD: true,
            subtitulada: true,
            PEGI: peliculas[7].PEGI,
            sinopsis: peliculas[7].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[7].estreno,
            poster: peliculas[7].poster,
            imagen: peliculas[7].imagen
        },
        {
            id: 21,
            id_pelicula: peliculas[8].id,
            nombre: peliculas[8].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[8].PEGI,
            sinopsis: peliculas[8].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[8].estreno,
            poster: peliculas[8].poster,
            imagen: peliculas[8].imagen
        },
        {
            id: 22,
            id_pelicula: peliculas[8].id,
            nombre: peliculas[8].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[8].PEGI,
            sinopsis: peliculas[8].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[8].estreno,
            poster: peliculas[8].poster,
            imagen: peliculas[8].imagen
        },
        {
            id: 23,
            id_pelicula: peliculas[8].id,
            nombre: peliculas[8].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[8].PEGI,
            sinopsis: peliculas[8].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[8].estreno,
            poster: peliculas[8].poster,
            imagen: peliculas[8].imagen
        },
        {
            id: 24,
            id_pelicula: peliculas[9].id,
            nombre: peliculas[9].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[9].PEGI,
            sinopsis: peliculas[9].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[9].estreno,
            poster: peliculas[9].poster,
            imagen: peliculas[9].imagen
        },
        {
            id: 25,
            id_pelicula: peliculas[9].id,
            nombre: peliculas[9].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[9].PEGI,
            sinopsis: peliculas[9].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[9].estreno,
            poster: peliculas[9].poster,
            imagen: peliculas[9].imagen
        },
        {
            id: 26,
            id_pelicula: peliculas[10].id,
            nombre: peliculas[10].nombre,
            tresD: true,
            subtitulada: false,
            PEGI: peliculas[10].PEGI,
            sinopsis: peliculas[10].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[10].estreno,
            poster: peliculas[10].poster,
            imagen: peliculas[10].imagen
        },
        {
            id: 27,
            id_pelicula: peliculas[10].id,
            nombre: peliculas[10].nombre,
            tresD: true,
            subtitulada: true,
            PEGI: peliculas[10].PEGI,
            sinopsis: peliculas[10].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[10].estreno,
            poster: peliculas[10].poster,
            imagen: peliculas[10].imagen
        },
        {
            id: 28,
            id_pelicula: peliculas[11].id,
            nombre: peliculas[11].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[11].PEGI,
            sinopsis: peliculas[11].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[11].estreno,
            poster: peliculas[11].poster,
            imagen: peliculas[11].imagen
        },
        {
            id: 29,
            id_pelicula: peliculas[11].id,
            nombre: peliculas[11].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[11].PEGI,
            sinopsis: peliculas[11].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[11].estreno,
            poster: peliculas[11].poster,
            imagen: peliculas[11].imagen
        },
        {
            id: 30,
            id_pelicula: peliculas[11].id,
            nombre: peliculas[11].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[11].PEGI,
            sinopsis: peliculas[11].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[11].estreno,
            poster: peliculas[11].poster,
            imagen: peliculas[11].imagen
        },
        {
            id: 31,
            id_pelicula: peliculas[12].id,
            nombre: peliculas[12].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[12].PEGI,
            sinopsis: peliculas[12].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[12].estreno,
            poster: peliculas[12].poster,
            imagen: peliculas[12].imagen
        },
        {
            id: 32,
            id_pelicula: peliculas[12].id,
            nombre: peliculas[12].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[12].PEGI,
            sinopsis: peliculas[12].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[12].estreno,
            poster: peliculas[12].poster,
            imagen: peliculas[12].imagen
        },
        {
            id: 33,
            id_pelicula: peliculas[12].id,
            nombre: peliculas[12].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[12].PEGI,
            sinopsis: peliculas[12].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[12].estreno,
            poster: peliculas[12].poster,
            imagen: peliculas[12].imagen
        },
        {
            id: 34,
            id_pelicula: peliculas[13].id,
            nombre: peliculas[13].nombre,
            tresD: false,
            subtitulada: false,
            PEGI: peliculas[13].PEGI,
            sinopsis: peliculas[13].sinopsis,
            dia: 'todos',
            horario: 1400,
            estreno: peliculas[13].estreno,
            poster: peliculas[13].poster,
            imagen: peliculas[13].imagen
        },
        {
            id: 35,
            id_pelicula: peliculas[13].id,
            nombre: peliculas[13].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[13].PEGI,
            sinopsis: peliculas[13].sinopsis,
            dia: 'todos',
            horario: 1900,
            estreno: peliculas[13].estreno,
            poster: peliculas[13].poster,
            imagen: peliculas[13].imagen
        },
        {
            id: 36,
            id_pelicula: peliculas[13].id,
            nombre: peliculas[13].nombre,
            tresD: false,
            subtitulada: true,
            PEGI: peliculas[13].PEGI,
            sinopsis: peliculas[13].sinopsis,
            dia: 'todos',
            horario: 2200,
            estreno: peliculas[13].estreno,
            poster: peliculas[13].poster,
            imagen: peliculas[13].imagen
        },
    ]